require 'sidekiq/api'

namespace :documents_collector do
  desc "[GIDAPPF]: Documents generated by Active Jobs..."
  task schedule_init: :environment do

    q = Sidekiq::Queue.new
    q.clear
    GidappfDocumentsCollectorJob.set(wait: 30.seconds).perform_later

  end

end
